import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Archivo } from "next/font/google";

const archivo = Archivo({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Jobstell | Official",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${archivo.className} antialiased`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
